[package]
name = "nopain"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.19" 
serde = {version = "1.0.209", features = ["derive"]}
clap = { version = "4.5.16", features = ["derive"] }
thiserror = "1.0.63"
chrono = {version = "0.4.38", features = ["serde"] }
#lazy_static = "1.5.0"
